### ISSUE TITLE
Cannot access replies to top level comments

### ISSUE THREAD

**Issue by pablooliveira** [halcyonnouveau/roux#16]
Thanks for working on roux !

I'm currently trying to parse the full comment tree for a given post. Unfortunately, I can only access top level comments. 
When looking at the original `.json` output from reddit API, each comment has a `replies` attribute that contains the children comments.

It seems the `replies` attribute is missing from the returned comments listing in roux.

**Comment by beanpuppy** [comment]
Cheers for the report, I'm surprised I missed that. 

Added with commit 3b7e1c6b2cee022dac52e871cc38aa4a28e0574a, so v1.1.1 will get published later today.

**Comment by pablooliveira** [comment]
Thanks @beanpuppy, that was quick !
