### ISSUE TITLE
Errors while trying to access subreddit data

### ISSUE THREAD

**Issue by magicaltoast** [halcyonnouveau/roux#18]
Hi, I am new to rust so I am sorry in advance if this issue is my fault.
I was trying to use an example from docs, and I got the following error.

> thread 'main' panicked at 'not currently running on the Tokio runtime.'

I did my research and I found out that probably roux expect tokio runtime but when I wrapped the main function with #[tokio::main] I am still getting the same error.

**Whole code**
```rust
use roux::Subreddit;
use tokio;

#[tokio::main]
async fn main() {
    let subreddit = Subreddit::new("rust");
    let rising = subreddit.rising(30, None).await;
    println!("{:?}", rising)
}
```
_Code above is a shortened version of [Basic Usage](https://docs.rs/roux/1.1.1/roux/subreddit/index.html#basic-usage)_

**Environment**
- Rust - 1.47.0
- Roux - 1.1.3
- Tokio - 0.3.0, features = ["full"]
- OS - Manjaro

Thanks in advance for any suggestion or solution <3 Have a nice day :)

**Comment by beanpuppy** [comment]
Hey thanks for the report.

There seems to be some sort of issue with the latest Tokio version (0.3) which is a beta release. Judging by the changelog, they made some changes to the runtime API: https://github.com/tokio-rs/tokio/pull/2876 so I think it might be a bug.

Anyway, I suggest to just downgrade to v0.2.22 as I can verify that it worked for me. Let me know how that goes.

**Comment by magicaltoast** [comment]
After changing tokio version everything works as expected. 
I should have checked cargo.toml, thanks for help, have a nice day :+1:
