### ISSUE TITLE
No syntax highlighting in docs.rs docs and are in a poor state.

### ISSUE THREAD

**Issue by beanpuppy** [halcyonnouveau/roux#22]
Probably because `should_fail` is given as an attribute in the code blocks so that tests still pass. To get both to work, we should follow [this part](https://doc.rust-lang.org/rustdoc/documentation-tests.html#hiding-portions-of-the-example) of the Rust docs: 

> Yes, that's right: you can add lines that start with `#`, and they will be hidden from the output, but will be used when compiling your code. You can use this to your advantage. In this case, documentation comments need to apply to some kind of function, so if I want to show you just a documentation comment, I need to add a little function definition below it. At the same time, it's only there to satisfy the compiler, so hiding it makes the example more clear. You can use this technique to explain longer examples in detail, while still preserving the testability of your documentation.

The documentation itself is also pretty bad and needs some work.

**Comment by frogtd** [comment]
`should_fail` isn't a thing that exists, perhaps you meant `should_panic` but you probably actually wanted to use `no_run`.
