### ISSUE TITLE
Missing fields in responses.

### ISSUE THREAD

**Issue by beanpuppy** [halcyonnouveau/roux#28]
There seem to be a lot of missing fields in many of the responses, would be good to have them even if they are unimportant.

Keep in mind that the Reddit API sucks pee pee, so there will need to be some testing to make sure that the fields actually always come through or not (meaning they'll need to be `Optional`). For some responses it might be that all fields can become `Optional` just for consistency.

**Comment by wherkamp** [comment]
I was thinking combine https://github.com/halcyonnouveau/roux/tree/master/src/subreddit/responses and https://github.com/halcyonnouveau/roux/tree/master/src/user/responses
As much as possible because the comments and submissions are the same responses and we have less code to update.

**Comment by beanpuppy** [comment]
@wherkamp yeah you're right about that. I looked at some other libraries and they've done the same. If you want to make a pull request with your commit, I'll merge it.
