### ISSUE TITLE
Using Me for better requests

### ISSUE THREAD

**Issue by wyatt-herkamp** [halcyonnouveau/roux#29]
# Issue 
A. If you pull data from a subreddit you are a making this query without the truly proper headers. You are missing a proper USER_AGENT
B. You are unable to pass the Authorization Bearer header and you wont be able to access private subs. 
# Solution
Subreddit::new_with_me(name: String, me:  &Me) having a new instance method that takes in Me. So proper headers can be used. 

# Ideas also to add with this.
Me#subreddit(name: String) -> Subreddit
Me#user(user: String) -> User

Allowing you to be able to create these structures easier with Me. 

I would also suggest  moving https://github.com/halcyonnouveau/roux/blob/master/src/me/mod.rs#L111
This to the Subreddit Object and requiring a present Me object.  I think it would be more organized.

**Comment by beanpuppy** [comment]
Sorry for the late response mate, I've been a bit swamped with work.

> Subreddit::new_with_me(name: String, me: &Me) having a new instance method that takes in Me. So proper headers can be used.

> Me#subreddit(name: String) -> Subreddit
> Me#user(user: String) -> User

Yep, all these seem good to me. I have no problem with them.

> I would also suggest moving https://github.com/halcyonnouveau/roux/blob/master/src/me/mod.rs#L111
> This to the Subreddit Object and requiring a present Me object. I think it would be more organized.

I'm a little bit more unsure about this one. I'd prefer to have the oauth stuff away from the non-oauth. I get that adding a `Me` struct to `Subreddit` would make it oauth, but you should still be able to access everything in Subreddit without the `Me`.

Oauth implies user sessions and I'd think it would be easier for people to understand that there's only **one** place to get them. 

Not a huge deal, I'll be willing to do it if there's a compelling enough reason.
