### ISSUE TITLE
Announcement: roux-stream provides a firehose-style streaming API for submissions and comments

### ISSUE THREAD

**Issue by torfsen** [halcyonnouveau/roux#37]
_(I'm not sure whether this is the right place for an announcement like this. Feel free to close as you see fit.)_

I've just released the first version of [`roux-stream`](https://docs.rs/roux-stream), a crate that provides a firehose-style API for streaming new submissions and comments from a subreddit (provided as a `roux::subreddit::Subreddit` instance). Examples of how to do that are included [in the documentation](https://docs.rs/roux-stream/0.1.0/roux_stream/fn.stream_submissions.html), a more detailed example can be found [in the project's repository](https://github.com/torfsen/roux-stream/blob/65c27885d11d760fc03bfa445fd989504a59e41f/examples/submissions-and-comments.rs).

I'm not sure whether you're interested in maintaining links to such 3rd-party libraries in the docs of `roux` itself. Let me know if you do, I'd be happy to prepare a PR.

**Comment by beanpuppy** [comment]
Sorry for the late reply, I've been on holiday. But thanks for making this, it's been something I've wanted to add but never got the time to work on or look at. 

> I'm not sure whether you're interested in maintaining links to such 3rd-party libraries in the docs of roux itself. Let me know if you do, I'd be happy to prepare a PR.

That'd be good, thanks.
