### ISSUE TITLE
Documentation for the "dist" field in Listing

### ISSUE THREAD

**Issue by Multirious** [halcyonnouveau/roux#52]
According to [this article](https://alpscode.com/blog/scripting-with-reddit-api/#:~:text=Here%2C%20the%20data%20you%20can%20use%20is%20inside%20the%20children%20array.%20Reddit%20makes%20our%20lives%20easy%20here%20by%20giving%20us%20how%20many%20elements%20the%20children%20array%20has%20%22dist%22%3A%205.%20Let%E2%80%99s%20see%20what%20the%20first%20child%20includes%3A), "dist" is just length of the child array. Should the doc update to that?

**Comment by beanpuppy** [comment]
Yep, going through a few examples, that seems to be the case. I've updated the docstring, thanks!
