### ISSUE TITLE
Headers for endpoints other than Me

### ISSUE THREAD

**Issue by Stumblinbear** [halcyonnouveau/roux#54]
Currently it's not possible to use the access token to call many of the endpoints, meaning accessing data from private or restricted communities is not really possible. It also means the bot headers aren't properly sent, such as the user agent which is against what Reddit asks bot developers to do

**Comment by beanpuppy** [comment]
Thanks for bringing this up. I've added the ability to create an authenticated `Subreddit` instance from the `Reddit` module in b5bd20a5bdcf3b441b13a59dd1e37549f803ebb9.
