### ISSUE TITLE
Use authentication with read-only module

### ISSUE THREAD

**Issue by MindSwipe** [halcyonnouveau/roux#61]
I'm trying to get comments from a subreddit which is private, is there a way to read from private from private subreddits? (Somewhat also applies to roux-stream)

**Comment by beanpuppy** [comment]
Yes, you can use `subreddit` instead of `login` on the `Reddit` module. E.g

```rust
let subreddit = Reddit::new("USER_AGENT", "CLIENT_ID", "CLIENT_SECRET")
    .username("USERNAME")
    .password("PASSWORD")
    .subreddit("rust")
    .await;
```

This gives you an authenticated subreddit module.

**Comment by beanpuppy** [comment]
I wouldn't know about roux-stream, you'd have to ask them, I'm not sure if it's updated anymore.
